name: CD Pipeline
on: push:
  branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no  ssh -i "C:\Users\stu\Downloads\pem\my-ec2-key.pem" ubuntu@ec2-18-217-146-140.us-east-2.compute.amazonaws.com << 'EOF'
          cd /home/ubuntu/fastapi-book-project
          git pull origin main
          sudo systemctl restart nginx
          EOF
